In [1]:
import numpy as np

In [2]:
# Create NumPy Array

In [3]:
arr = np.array([1, 2, 3, 4, 5])

In [4]:
print(arr)

[1 2 3 4 5]


In [5]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
# python list

a = [1, 2, 3, 4]
b = [5, 6, 7, 8]

type(a), type(b)

(list, list)

In [7]:
a + b

[1, 2, 3, 4, 5, 6, 7, 8]

In [8]:
arrayA = np.array(a)
arrayB = np.array(b)

type(arrayA), type(arrayB)

(numpy.ndarray, numpy.ndarray)

In [9]:
arrayA * arrayB
arrayA / arrayB

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [10]:
arrayA * 10 # broadcasting

array([10, 20, 30, 40])

In [11]:
y_pred = np.array([1,0, 0, 1, 1, 0, 1, 1])
labels = np.array([0,1,0,1,1,0,1,1])

mse = (1/len(labels)) * np.sum(np.square(y_pred - labels))
print(mse)

0.25


In [12]:
# Create NumPy Array 0 Dimention (0D)

In [13]:
arr = np.array(45)

In [14]:
print(arr)

45


In [15]:
# Create NumPy Array 0 Dimention (1D)

In [16]:
arr = np.array([1,2,3,4,5])

In [17]:
print(arr)

[1 2 3 4 5]


In [18]:
# Create NumPy Array 0 Dimention (2D)

In [19]:
arr = np.array(([1,2,3], 
                [4,5,6]))

In [20]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [21]:
# Create NumPy Array 0 Dimention (3D)

In [22]:
arr = np.array([[[1, 2, 3], [4, 5, 6]],
                [[6, 7, 8], [7, 8, 9]]])

In [23]:
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[6 7 8]
  [7 8 9]]]


In [24]:
# Create NumPy Array 0s and 1s

In [25]:
arr = np.zeros(5)

In [26]:
print(arr)

[0. 0. 0. 0. 0.]


In [27]:
arr = np.zeros((5, 2))
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [28]:
arr = np.ones((7,7))

In [29]:
print(arr)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [30]:
arr = np.ones((3,4,2))

In [31]:
print(arr)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [32]:
arr = np.array ([[1,2,3], [4,5,6], [7,8,9]])
arr = np.delete(arr, 1, axis=0)

In [33]:
# Delete Array

In [34]:
arr = np.array ([[1,2,3], [4,5,6], [7,8,9]])
arr = np.delete(arr, 1, axis=0)

In [35]:
print(arr)

[[1 2 3]
 [7 8 9]]


In [36]:
del arr

In [37]:
# Element Accessing at NumPy Array 1D

In [38]:
arr = np.array([1,2,3,4])

In [39]:
arr[1: -1]

array([2, 3])

In [40]:
# Element Accessing at NumPy Array 2D

In [41]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [42]:
print(arr[1, 4])

10


In [43]:
print(arr[1, -1])

10


In [44]:
print(arr[1, 1:4])

[7 8 9]


In [45]:
# Checking Data Type At NumPy Array

In [46]:
arr = np.array([1,2,3,4])

In [47]:
print(arr.dtype)

int32


In [48]:
arr = np.array([1,2,3,4,], dtype='S')

In [49]:
print(arr)

[b'1' b'2' b'3' b'4']


In [50]:
arr = np.array([1,2,3,4,], dtype='I')

In [51]:
print(arr)

[1 2 3 4]


In [52]:
print(arr.dtype)

uint32


In [53]:
arr = np.array([1,2,3,4,], dtype=np.int32)

In [54]:
print(arr)

[1 2 3 4]


In [55]:
print(arr.dtype)

int32


In [56]:
# Changing Data Type at NumPy Array

In [57]:
arr = np.array([1.5,2.5,3.5])

In [58]:
arr

array([1.5, 2.5, 3.5])

In [59]:
arr = arr.astype('I')

In [60]:
arr

array([1, 2, 3], dtype=uint32)

In [61]:
print(arr.dtype)

uint32


In [62]:
# Arange Function

In [63]:
arr = np.arange(15)

In [64]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [65]:
print(type(arr))

<class 'numpy.ndarray'>


In [66]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [67]:
arr = np.arange(10, 20)

In [68]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [69]:
arr = np.arange(10, 20, 2)

In [70]:
arr

array([10, 12, 14, 16, 18])

In [71]:
arr = np.arange(-1, 1, 0.1)
arr

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])