In [1]:
##Getting Shape At Array

In [2]:
import numpy as np

In [3]:
arr = np.array([[1,2,3,4], [5,6,7,8]])

In [4]:
print(arr.shape)

(2, 4)


In [5]:
print(arr.size) #volume element

8


In [6]:
print(arr.ndim) #volume shape

2


In [7]:
## using ndmin for dimension definition

In [8]:
arr = np.array([1,2,3,4], ndmin=3)

In [9]:
arr

array([[[1, 2, 3, 4]]])

In [10]:
print(arr.shape) # dimension

(1, 1, 4)


In [11]:
print(arr.ndim) # know dimension volume

3


In [12]:
## Reshape from 1D to 2D

In [13]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [14]:
arr.shape # volume element

(12,)

In [15]:
arr = arr.reshape(4, 3) # keep element with different shape

In [16]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [17]:
arr.ndim # volume shape

2

In [18]:
# Reshape from 1D to 3D

In [19]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [20]:
arr = arr.reshape(2,3,2) # changing shape with keep element

In [21]:
arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [22]:
arr.shape # overview create shape

(2, 3, 2)

In [23]:
arr.ndim # volume shape

3

In [24]:
# Using -1 at reshaping proccess

In [25]:
arr = np.array([1,2,3,4,5,6,7,8]) # attention same element, can change shape

In [26]:
arr = arr.reshape(2,2, -1)

In [27]:
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [28]:
arr.shape

(2, 2, 2)

In [29]:
# Flattening at Array

In [30]:
arr = np.array([[1,2,3,], [4,5,6]])

In [31]:
arr = arr.reshape(-1)

In [32]:
print(arr)

[1 2 3 4 5 6]


In [33]:
arr = np.array([[1,2,3], [4,5,6]])

In [34]:
arr = arr.flatten()

In [35]:
print(arr)

[1 2 3 4 5 6]


In [36]:
# Duplication for array using Copy()

In [37]:
arr = np.array([1,2,3,4,5])
x = arr.copy()

In [38]:
arr[0] = 42

In [39]:
arr

array([42,  2,  3,  4,  5])

In [40]:
x # keep copy for original array

array([1, 2, 3, 4, 5])

In [41]:
# Duplication for array using View()

In [42]:
arr = np.array([1,2,3,4,5])
x = arr.view()

In [43]:
arr[0] = 42

In [44]:
arr

array([42,  2,  3,  4,  5])

In [45]:
x # adjust for array changing because just view

array([1, 2, 3, 4, 5])