In [1]:
## Iterasi at NumPy Array 1D

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3])

In [4]:
for x in arr:
    print(x)

1
2
3


In [5]:
# Iterasi at NumPy Array 2D

In [6]:
arr = np.array([[1,2,3], [4,5,6]])

In [7]:
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [8]:
# Iterasi at NumPy Array 3D

In [9]:
arr = np.array([[[1,2,3], [4,5,6]],
                [[7,8,9], [10,11,12]]])

In [10]:
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [11]:
# Iterasi with nditer()

In [12]:
arr = np.array([[[1,2], [3,4], [5,6], [7,8]]])

In [13]:
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [14]:
# Iterasi with ndenumerate() at Array 1D 

In [15]:
arr = np.array([1,2,3])

In [16]:
for idx, x in np.ndenumerate(arr): # with index
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [17]:
# Iterasi with ndenumerate() at Array 2D

In [18]:
arr = np.array([[1,2,3], [4,5,6]])

In [19]:
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [20]:
##Join with 2 Array 1D

In [21]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [22]:
arr = np.concatenate((arr1, arr2))

In [23]:
print(arr)

[1 2 3 4 5 6]


In [24]:
##Join with 2 Array 2D

In [25]:
arr1 = np.array([[1, 2],[3, 4]])
arr2 = np.array([[5, 6],[7, 8]])

In [26]:
arr =np.concatenate ((arr1, arr2), axis=1)

In [27]:
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [28]:
arr.shape

(2, 4)

In [29]:
## Stack for 2 Array 1D

In [30]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [31]:
arr = np.stack((arr1, arr2))

In [32]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [33]:
arr.shape

(2, 3)

In [34]:
## Stack for 2 Array 1D using hstack()

In [35]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [36]:
arr = np.hstack((arr1, arr2))

In [37]:
print(arr)

[1 2 3 4 5 6]


In [38]:
## Stack for 2 Array 1D using Vstack()

In [39]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [40]:
arr = np.vstack((arr1, arr2))

In [41]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [42]:
## Split for 1 Array 1D

In [43]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [44]:
arr = np.array_split(arr, 3)

In [45]:
print(arr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [46]:
## Split for 2 Array 2D

In [47]:
arr = np.array([[1, 2], [3, 4], [5, 6], 
                [7, 8], [9, 10], [11, 12]])

In [48]:
arr = np.array_split(arr, 2)

In [49]:
arr

[array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])]

In [50]:
## Search at Array 1D

In [51]:
arr = np.array ([1, 2, 3, 4, 5, 4, 4])

In [52]:
x =  np.where(arr == 4)

In [53]:
print(x)

(array([3, 5, 6], dtype=int64),)


In [54]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

In [55]:
x = np.where(arr**2 == 4)

In [56]:
print(x)

(array([1], dtype=int64),)


In [57]:
## Sort at Array 1D

In [58]:
arr = np.array([3, 2, 0, 1])

In [59]:
print(np.sort(arr))

[0 1 2 3]


In [60]:
arr = np.array(['banana', 'watermelon', 'apple'])

In [61]:
print(np.sort(arr))

['apple' 'banana' 'watermelon']


In [62]:
## Sort at Array 2D

In [63]:
arr = np.array([[5,3,6], [7,2,9]])

In [64]:
print(np.sort(arr))

[[3 5 6]
 [2 7 9]]
