In [1]:
# Get integer number by random

In [2]:
from numpy import random

In [3]:
x = random.randint(100)

In [4]:
x

35

In [5]:
# Get float number by random

In [6]:
x = random.rand()

In [7]:
x

0.933254670367825

In [8]:
# Create Array 1D with integer value by random

In [9]:
x = random.randint(100, size=(7))

In [10]:
x

array([28, 98, 49, 72, 32, 34, 18])

In [11]:
# Create Array 2D with integer value by random

In [12]:
x = random.randint(100, size=(5, 9))

In [13]:
x

array([[56, 77, 69, 54, 67,  6, 76, 98, 70],
       [37, 20,  3,  0, 76, 35, 38, 82, 84],
       [ 4, 38, 31, 88, 24, 99, 46, 11, 80],
       [77, 82, 90, 71, 39, 19, 51,  4,  9],
       [29, 56, 90, 81, 44, 50, 75, 70, 54]])

In [14]:
# Create Array 1D with float value by random

In [15]:
x = random.rand(9)

In [16]:
x

array([0.18364018, 0.99220107, 0.10118706, 0.81990121, 0.53253276,
       0.47820755, 0.90105749, 0.30859744, 0.15303173])

In [17]:
# Create Array 1D with float value by random

In [18]:
x = random.rand(5, 3)

In [19]:
x

array([[0.374507  , 0.29885545, 0.63121723],
       [0.59845055, 0.64960294, 0.6464531 ],
       [0.92070302, 0.23643072, 0.38484155],
       [0.34936786, 0.49683517, 0.62558547],
       [0.33437726, 0.31846912, 0.04205008]])

In [20]:
# Create random integer value by Array 1D

In [21]:
x = random.choice([3, 5, 7, 9])

In [22]:
x

7

In [23]:
# scrambler random existing values at Array 1D

In [24]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

In [25]:
random.shuffle(arr)

In [26]:
print(arr)

[4 3 1 2 5]
